on: push
name: Validate
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      #kubeval action
    - uses: actions/checkout@master
    - name: test
      uses: instrumenta/kubeval-action@master
      #kube-score action
    - name: Checkout
      uses: actions/checkout@master
    - name: kube-score check
      uses: piraces/kube-score-ga@master
      with:
        manifests-folders: './manifests/*.yml'
